# See config.example.yml for documentation.
object: orig/RM8E01/DATA/sys/main.dol
hash: 02e650379eea467ee5b57db0a14d6b737252aae0
symbols: config/RM8E01/symbols.txt
splits: config/RM8E01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
